### ISSUE TITLE
Formula: double check near-exact values

### ISSUE THREAD

**Issue by zross** [WHOequity/who-heat#138]
For MLD and TI I found that the calculations I was producing were three orders of magnitude smaller than WHO but otherwise the same. I multiplied by 1000 and this worked.

For RCI I found the values two orders of magnitude smaller than WHO so I multiplied by 100 and this worked.

For RD I was getting some negative values but otherwise the same. So I made this absolute value and this produced the same values.

Not sure the reasons and if my solutions are appropriate.

**Comment by WHOequity** [comment]
Yes, we multiplied MLD and TI by 1000 and RCI by 100 (otherwise the values are too small!). The toolkit actually has an option to display MLD and TI values multiplied by 1000 and to display RCI multiplied by 100 (see screenshot below). Not sure what the calculations in the codes should be then. 

We are not taking the absolute value of RD and also obtain a few negative values. In which cases did you obtain negative values?

**Comment by zross** [comment]
Ah, I see. If I included the multiplication by 1000 and 100 in the formulas we can drop those check boxes. Can we drop the MLD and TI multiplication? This seems unnecessary to me.

**Comment by WHOequity** [comment]
It would be good to keep the option (but the default display should be MLD and TI multiplied by 1000 and RCI multiplied by 100). It would be good to a title and change the labels for the check boxes: 
- Select estimate display
  - MLD and TI multiplied by 1000
  - RCI multiplied by 100
