### ISSUE TITLE
Bug: is there a problem in your RD calculations?

### ISSUE THREAD

**Issue by zross** [WHOequity/who-heat#140]
@WHOequity my `rd` estimates and yours match mostly but there are several instances where I'm negative and you're positive as well as instances where the reverse is true. If the `r` value for a more advantaged group is LOWER than the less advantaged group shouldn't this be negative?

**Here is an example where I have positive numbers and you have negative numbers**
```
  country  year source indic          dimension subgroup        r order
Jordan  2012    DHS asfr1 Place of residence    Rural 17.95513     1
Jordan  2012    DHS asfr1 Place of residence    Urban 29.05581     2
```

Your value is: -11.10
My value is: 11.10

**Here is an example where I have negative numbers and you have positive numbers**

```
  country  year source indic          dimension subgroup        r order
Albania  2008    DHS asfr1 Place of residence    Rural 24.72746     1
Albania  2008    DHS asfr1 Place of residence    Urban 12.42709     2
```

Your value is: 12.30
My value is: -12.30

**Comment by zross** [comment]
This also seems to be an issue with the calculation of `riikm`. For the exact same example where I have negative and you have positive above the same is true of `riikm`. So Albania example:

Your value is: 12.32
My value is: -12.32

**Comment by WHOequity** [comment]
If RD is calculated for an outcome indicator and a rankable dimension, then it is calculated as: RD = "most-disadvantaged" - "most-advantaged". 

The indicator asfr1 is an outcome indicator with a minimum optimum (maxoptimum=0) and the dimension place of residence is a "rankable" dimension (rankable=1) with rural being the most-disadvantaged subgroup (order=1) and urban being the most-advantaged subgroup (order=2). In this case, RD should be calculated as: RD = Rural - Urban. In the above example, this yields a positive estimate. 

I'm assuming the same is true for the RIIKM example. 

I'm not sure what the problem is. Before, place of residence was not treated as a rankable dimension, but it's listed as a rankable dimension in the database I shared with you.

**Comment by zross** [comment]
Was RD calculated in the app previously for the examples I show? Is it supposed to use maxoptimum -- it is not used in his code. In the code he has it as:

`RD = most-advantaged - most disadvantaged`

The odd thing is that several give the same answer as yours.

**Comment by WHOequity** [comment]
Yes, absolutely right! That's what we expect! But the formula is incorrect (and I am suspecting that the formula for RR is also incorrect, because they both should follow the same logic).

- For nonrankable dimensions (rankable=0), we calculate RD as: RD = maximum - minimum
- For rankable dimensions (rankable==1), we calculate RD
-- in the case of intervention indicators (maxoptimum=1) as: RD = most-advantaged - most-disadvantaged
-- in the case of outcome indicators (maxoptimum=0) as: RD = most-disadvantaged - most-advantaged

This is because in the case of intervention indicators, the most-advantaged tend to have higher estimates than the most-disadvantaged, whereas the opposite is true in the case of outcome indicators. We reverse the calculation in order to obtain positive estimates in the majority of cases.

**Comment by zross** [comment]
So is your formula incorrect or is the R formula incorrect? Take a look at the example below. 

This is rankable and maxoptimimum is 1 so shouldn't it be most-advantaged - most-disadvantaged?

If so we have 99.5225 - 99.80702 = -0.284523. This is what R calculates but what you sent me has positive 0.284. This looks like the R formula is correct.



```
  country  year source indic       dimension             subgroup        se         r order maxoptimum
    (chr) (dbl)  (chr) (chr)           (chr)                (chr)     (dbl)     (dbl) (dbl)      (dbl)
1 Armenia  2010    DHS  anc1 Economic status Quintile 1 (poorest) 0.1955696  99.80702     1          1
2 Armenia  2010    DHS  anc1 Economic status           Quintile 2 0.5944933  99.40836     2          1
3 Armenia  2010    DHS  anc1 Economic status           Quintile 3 0.0000000 100.00000     3          1
4 Armenia  2010    DHS  anc1 Economic status           Quintile 4 1.4980371  97.77782     4          1
5 Armenia  2010    DHS  anc1 Economic status Quintile 5 (richest) 0.4807410  99.52250     5          1
```

**Comment by zross** [comment]
For recording purposes: the `rr` function uses maxoptimum and does some altering of which are high and which are low but `rd` did not have anything similar.

**Comment by WHOequity** [comment]
Agreed that the R formula for RD is correct. But I see the same result (negative estimate) for the above example in our excel file.

**Comment by zross** [comment]
You're right! I got them reversed. The r script had the issue and I have it fixed.

**Comment by zross** [comment]
For reference purposes:

anc1 = maxoptimum is 1
asfr1 = maxoptimum is 0

**Comment by WHOequity** [comment]
Yes, that's correct.
