### ISSUE TITLE
If time permits: adjust column width for full names in tables

### ISSUE THREAD

**Issue by WHOequity** [WHOequity/who-heat#203]
Is it possible to adjust the column width of individual columns in tables? It would be good if the columns for full indicator names and full summary measure names were a bit wider, so that the table doesn't become too long (even though this means, that it will become wider).

**Comment by zross** [comment]
This was trickier than I expected because the columns can sometimes be in different locations (if there are many columns, indicator name is always at the fourth column) but if the user deletes most columns it can be at the 1st, 2nd or 3rd. 

Anyway, this is done. If you want a change to the widths I chose that is easy. Indicator name is 200px and summary measure name is 100px.

please close if done
