### ISSUE TITLE
Handling of missing data: missing data for some subgroups

### ISSUE THREAD

**Issue by WHOequity** [WHOequity/who-heat#227]
If disaggregated data are missing for some subgroups of a selected country-year-indicator-dimension combination, this should be handled as follows:

![untitled](https://cloud.githubusercontent.com/assets/13563065/11215411/4dfe4ce8-8d46-11e5-81a0-e604d4f31b03.png)

**Comment by WHOequity** [comment]
Examples where this is not correctly implemented: 

- Case 1 (ONLY the country-year-indicator-dimension combination with missing data for some subgroups is selected): Armenia, DHS 2010, anc1 (2 or 3 years) by education
  - The Explore Inequality - Summary measures graphs (line and bar graphs) give the error message “Error: ‘from’ must be of length XX” (which is incorrect).

**Comment by zross** [comment]
What do you mean by "graphs with missing data displayed" when all the data is missing? Take a look now, for the summary measure graph I put the warning since there is no data for summary graph. The summary table shows a blank value. :The disag graph shows any value avail and the disag data shows all data but blanks where missing.

**Comment by WHOequity** [comment]
Looking good for all disaggregated data tables and graphs! I also agree with the summary measure tables. 

But I think we should be consistent for summary measure graphs: either we don't show the graphs if data for the main country of interest are missing or we do show them (with the disclaimer displayed on top of the graph). Right now, the Explore Inequality graphs are not shown at all, while the Compare Inequality graph is shown (without disclaimer). What do you think?

**Comment by WHOequity** [comment]
This is what I mean by empty graph (from an older version of HEAT): 

![untitled](https://cloud.githubusercontent.com/assets/13563065/11243091/487bd57c-8e06-11e5-8728-a00c04ed7a2d.png)

**Comment by zross** [comment]
This is your call. I removed the empty graph in explore because I thought it was confusing. When you say that Compare Inequality graph is shown (without disclaimer) you mean even if there is no data for any of the countries right? I think if there is no data for any countries we should not show graphs. Then I will add the disclaimer to the compare plots. Yes?

**Comment by WHOequity** [comment]
Yes, agreed to not show empty Explore Inequality (summary measure) graphs. The Compare Inequality (summary measure) graph should not be shown at all, if the summary measure for the main country of interest (!) cannot be calculated.

Example: Armenia, DHS 2010, anc1 by education, benchmarked against all middle-income countries from the WHO European Region. Here, RD can only be calculated for one of the benchmark countries (Tajikistan). The graph should not be shown at all (because you cannot do any benchmarking for your country of interest). 

![untitled](https://cloud.githubusercontent.com/assets/13563065/11335697/c77d3006-91de-11e5-85c7-53f8f4d756c9.png)
