### ISSUE TITLE
If time permits: Change default view for Explore Inequality graphs

### ISSUE THREAD

**Issue by WHOequity** [WHOequity/who-heat#253]
By default, no 95% confidence intervals should be shown in graphs (workshop participants felt this made the graphs too busy). 
- For bar graphs, estimate numbers should be shown on top of the bars instead (as is now the case for the disaggregated data graphs; please also apply to summary measures graph). However, users should have the option to add 95% confidence intervals (as is now the case for the summary measures graphs; please also apply to disaggregated data graphs). 
- For summary measure line graphs, users should simply have the option to add the 95% confidence intervals (implemented already, please just change the default setting).

**Comment by WHOequity** [comment]
See also #200 and #205

**Comment by zross** [comment]
I have:
1. Changed default for line graphs so that CI does not show up unless clicked.
2. For bar graph by default CI does not show unless clicked. I also added numbers at top of bars. I made it so that the numbers disappear when the CI are added.

You say "please also apply to disaggregated data graphs" - I'm not sure what this refers to. There are no CI in disaggregated graphs and the numbers are already on top of the bars.
