### ISSUE TITLE
Functionality: remove "Fetch" button if possible

### ISSUE THREAD

**Issue by zross** [WHOequity/who-heat#42]
Benchmark countries

**Comment by zross** [comment]
@WHOequity when you say remove fetch button do you mean have it "live update". This would be fine (and better from my perspective) but how would you want to handle the initial view -- what should be loaded by default. 

Also do you want Fetch data removed from the explore inequality? I think if it's fast enough then this might be better. We'd need to define the starting parameters.

**Comment by WHOequity** [comment]
If we can remove the "Fetch data" button, the default selection would be the main country of interest, data sources, years, indicators and dimensions that have been selected under "Explore Inequality". By default, no benchmarking country should be selected (I think currently all countries are selected). 

Note that the table should be removed from the view. It takes a very long time to load the table if a lot of countries are selected. And to us it doesn't make much sense to only show the disaggregated data for all countries. If we do, we feel like we should also be showing the summary measure data for all countries (similar to what we have under "Explore Inequality"). But this is not really necessary as users will be able to download the data displayed in the graphs as .csv files.

**Comment by WHOequity** [comment]
The question is, however, what the default selection is when users go straight from the main home page to "Compare inequality". If users go from the main home page to "Explore inequality", they first have to select their variables of interest and then fetch the data. Should we keep a similar mechanism under "Compare inequality" (even though we are really encouraging and expecting users to move from home to "Explore inequality" to "Compare inequality") ?

**Comment by WHOequity** [comment]
I think this issue also depends on how we go about issue 9. Will users be able to select their main country of interest in the main home page (which then is the default selection in all tabs under "Explore inequality" and "Compare inequality")? And/or will the menu be completely flexible in all tabs (i.e. will users be able to change the country in each tab)? We haven't made a decision on this yet. It also depends on what is (most) feasible in R/Shiny. 

The original idea was for users to select their main country of interest in the beginning (on the main home page), for which they would then undertake the equity assessment: firstly, by "exploring inequality" in that country and secondly, by "comparing inequality" in that country with the situation in other countries. This way users would be expected to move from the home page to "explore inequality" to "compare inequality". The default selection in each tab would always be what the user has selected in the previous tab. 

Another idea was that the menu is completely flexible in all tabs, so that users can move quickly between different countries, sources, years, indicators and dimensions.

We are not sure what's better. It very much also depends on the feasibility and speed. What are your thoughts?

**Comment by zross** [comment]
removed
