### ISSUE TITLE
Bug: data with no estimate should not be included (?)

### ISSUE THREAD

**Issue by zross** [WHOequity/who-heat#93]
@WHOequity Right now data with no estimates are included in the disaggregated data. See Armenia, 2010, Children with ARI symptoms..., Geographic Region. This gives an error in the plots. Should I filter out the data with no estimate?

**Comment by zross** [comment]
See the Explore tab, change from "Sex" to geographic, now it does not return any records because none have estimates. Then look at the plot and I added a warning that the variables return no data. What do you think?

**Comment by WHOequity** [comment]
I think this is good, but will discuss and get back to you on this.

**Comment by WHOequity** [comment]
Can we handle missing data as follows: 
- Disaggregated data tables
  - show all data (including missings), if data is missing for some subgroups (e.g. dtp3 by education for Albania)
  - do not show any data, if data is missing for all subgroups (e.g. dtp3 by education for Afghanistan( or if selected variable combination is not available (e.g. data by economic status for Cuba) 
  - add disclaimer on top of of table: "If estimates are not shown for a selected combination of variables, then data is not available." (provisional text)
- Summary measures tables
  - show missing summary measures, if these measures cannot be calculated because data is missing for some subgroups
  - do not show missing summary measures, if these measures cannot be calculated because data is missing for all subgroup or if selected variable combination is not available
  - add disclaimer on top of table: "If summary measures are not shown for a selected combination of variables, then data is not available and summary measures cannot be calculated." (provisional text)
